### PR TITLE
FreeBSD compatibility patch.

### PR DESCRIPTION
**Pull request by yurivict**

### CODE REVIEW

**Comment by monocasual** [comment]
Thanks for this! However, we would really love to keep FreeBSD as a subset of our `G_OS_LINUX` define, even if it might sound like a heresy. 
Did you find any configuration/compilation errors while building Giada with `--target=linux` on FreeBSD?

**Comment by tblrchstr** [comment]
Honestly speaking I fear we don't have enough firepower to handle yet another platform. We already have a pretty messed-up build matrix like win with-vst, win without-vst, macos with-vst, macos without-vst, lin with-vst, lin without-vst. That said, @yurivict you did a great job and I vote for postponing this PR in a future where things will get more stable and ready to be shipped (and tested!) to more platforms.

**Comment by yurivict** [comment]
> Honestly speaking I fear we don't have enough firepower to handle yet another platform.

You don't need to handle anything. I've already created the port and these patches are what was required to make it work. They are currently in the port, but it would be nicer if they were upstreamed.

**Comment by monocasual** [comment]
OK folks, after a month of summer brainstorming we have come up with a solution. The idea of supporting FreeBSD is great and we would love to add it sooner or later. However, as @tblrchstr pointed out, we can't have a FreeBSD environment at the moment. For this reason it is very likely that, while adding new features, someone will forget to add the `defined(G_OS_FREEBSD)` where needed.  So, let's postpone this when we have reached version 1.0 and the feature list will be less "volatile" than now. I have just opened a new issue referencing this pull request, here: #200. Thank you @yurivict , you won't be forgotten...

**Comment by yurivict** [comment]
The FreeBSD port is available for a while: http://beta.freshports.org/audio/giada/

I only submitted the patches here as a matter of upstreaming them so that they wouldn't need to be maintained with the port.

Otherwise, the port is fine and no additional action is required from you besides merging this patch.

**Comment by yurivict** [comment]
Why don't you just merge this patch?

**Comment by monocasual** [comment]
> Why don't you just merge this patch?

As I wrote earlier, we can't support (i.e. build, test) FreeBSD at the moment. We'll wait version 1.0 when the stream of new features will settle down a bit.

**Comment by yurivict** [comment]
I am not asking you to officially declare that you support FreeBSD and test it. I only asked to merge the patch, because the port already exists. If it isn't merged, I will have to recreate it locally every time something changes around it.

**Pull request closed without merging**
